version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_HOST: mongo_db
      MONGODB_PORT: 27017
      DB_NAME: test-db
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
